---
title: "README"
author: "Beise"
date: "March 22, 2015"
output: html_document
---

There is one script which proceeds through all the steps prescribed by the problem in the following way:

Step 1 from Project Instruction - Merge the test and training datasets
  SubStep 1.1 - creating a Test/Train identifier to the subject tables
  SubStep 1.2 - rowbinding the test/train subject files to the subject_files
    for each row - output: a_subject
  SubStep 1.3 - rowbinding and labelling the test/train activity files -
    output: b_activity
  SubStep 1.4 - rowbinding the test and training data files and applying 
    colnames - output: c_data
  SubStep 1.5 - colbinding the subject file to the activity file to the data
    file - output: comb_raw
Step 2 - Extract the measurements on the mean and standard deviation for each
  measurement
  SubStep 2.1 - identify the variables of interest and subset on that list
Step 3 - apply activity name through merge
Step 4 - label data set with appropriate variable names
Step 5 - create tidy data set of average of each variable for each activity and each subject


